name: CI
on: [push, pull_request]

jobs:
  build-project:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_DATABASE_URL: ${{ secrets.DATABASE_URL }}
          envkey_NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          envkey_NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          envkey_NEXT_GITHUB_CLIENT_ID: ${{ secrets.NEXTAUTH_URL }}
          envkey_NEXT_GITHUB_CLIENT_SECRET: ${{ secrets.NEXT_GITHUB_CLIENT_SECRET }}
      - name: Install NPM dependencies
        run: pnpm install --no-frozen-lockfile
      - name: Run local server
        run: pnpm dev
